//! Guarding a loopback port.
//!
//! `127.0.0.1` is not a security boundary by itself. Any local process can reach
//! it, and — more subtly — so can any web page the user happens to visit, via
//! DNS rebinding. Four layers, all cheap, all mandatory:
//!
//! 1. **Ephemeral port.** Bound with `:0`, so there is no fixed target to probe.
//! 2. **Bearer token**, 256 bits, compared in constant time. Generated by the
//!    host and passed in the environment — never in argv, which is world-readable
//!    via `ps aux`.
//! 3. **`Host` allowlist.** This is what actually defeats DNS rebinding: an
//!    attacker can make `evil.com` resolve to `127.0.0.1`, but the browser will
//!    then send `Host: evil.com`, which we reject. Rebinding cannot forge `Host`.
//! 4. **`Origin` allowlist**, so a page cannot drive the API even if it somehow
//!    learned the port. Browsers always send `Origin` on a cross-origin fetch,
//!    and cannot forge it.
//!
//! Deliberately **not** a check: rejecting `Sec-Fetch-Site: cross-site`. Every
//! legitimate request here is cross-site — the renderer lives on `app://local`
//! and the API on `http://127.0.0.1:<port>` — so that rule rejects the only
//! traffic the server exists to serve. It was tried, and it broke everything.
//! The `Origin` allowlist expresses the same intent precisely.

use axum::extract::State;
use axum::http::{HeaderMap, StatusCode, header};
use axum::middleware::Next;
use axum::response::Response;
use subtle::ConstantTimeEq;

use crate::state::AppState;

/// Why a request was refused. Returned as a plain reason string — this API has
/// exactly one legitimate client, so there is nothing to be gained by being
/// vague, and a clear message saves hours during development.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Denied {
    MissingToken,
    BadToken,
    BadHost,
    BadOrigin,
}

impl Denied {
    const fn detail(self) -> &'static str {
        match self {
            Self::MissingToken => "missing Authorization: Bearer header",
            Self::BadToken => "invalid bearer token",
            Self::BadHost => "Host header does not match the bound loopback address",
            Self::BadOrigin => "Origin is not the allowed origin",
        }
    }

    const fn status(self) -> StatusCode {
        match self {
            Self::MissingToken | Self::BadToken => StatusCode::UNAUTHORIZED,
            Self::BadHost | Self::BadOrigin => StatusCode::FORBIDDEN,
        }
    }
}

/// Pure decision function, so the policy is testable without a running server.
pub fn check(headers: &HeaderMap, state: &AppState) -> Result<(), Denied> {
    // ── Host ─────────────────────────────────────────────────────────────────
    let host = headers.get(header::HOST).and_then(|v| v.to_str().ok());
    match host {
        // A request with no Host at all is HTTP/1.0 or handcrafted; the token
        // still gates it, and browsers always send one.
        None => {}
        Some(h) if state.is_allowed_host(h) => {}
        Some(_) => return Err(Denied::BadHost),
    }

    // ── Origin ───────────────────────────────────────────────────────────────
    // Absent Origin means a non-browser client, which the token already gates.
    // Present-but-wrong means a page is trying to drive us: refuse.
    if let Some(origin) = headers.get(header::ORIGIN).and_then(|v| v.to_str().ok())
        && !state.is_allowed_origin(origin)
    {
        return Err(Denied::BadOrigin);
    }

    // ── Bearer ───────────────────────────────────────────────────────────────
    let presented = headers
        .get(header::AUTHORIZATION)
        .and_then(|v| v.to_str().ok())
        .and_then(|v| v.strip_prefix("Bearer "))
        .ok_or(Denied::MissingToken)?;

    // Constant-time compare. The length check leaks only the length, which is a
    // compile-time constant anyway.
    let expected = state.token().as_bytes();
    if presented.len() != expected.len() || presented.as_bytes().ct_eq(expected).unwrap_u8() != 1 {
        return Err(Denied::BadToken);
    }

    Ok(())
}

/// Axum middleware wrapping [`check`].
pub async fn guard(
    State(state): State<AppState>,
    request: axum::extract::Request,
    next: Next,
) -> Result<Response, (StatusCode, String)> {
    match check(request.headers(), &state) {
        Ok(()) => Ok(next.run(request).await),
        Err(denied) => {
            tracing::warn!(reason = denied.detail(), "request refused");
            Err((denied.status(), denied.detail().to_owned()))
        }
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]
    use super::*;
    use axum::http::HeaderValue;

    fn state() -> AppState {
        AppState::for_test("s3cret-token-value", "app://local", 51234)
    }

    fn headers(pairs: &[(&str, &str)]) -> HeaderMap {
        let mut h = HeaderMap::new();
        for (k, v) in pairs {
            h.insert(
                header::HeaderName::from_bytes(k.as_bytes()).unwrap(),
                HeaderValue::from_str(v).unwrap(),
            );
        }
        h
    }

    #[test]
    fn accepts_a_well_formed_request() {
        let h = headers(&[
            ("host", "127.0.0.1:51234"),
            ("origin", "app://local"),
            ("authorization", "Bearer s3cret-token-value"),
        ]);
        assert_eq!(check(&h, &state()), Ok(()));
    }

    #[test]
    fn rejects_a_rebound_host() {
        // The DNS rebinding case: evil.com resolves to 127.0.0.1, but the
        // browser still sends the attacker's hostname in Host.
        let h = headers(&[
            ("host", "evil.example.com"),
            ("authorization", "Bearer s3cret-token-value"),
        ]);
        assert_eq!(check(&h, &state()), Err(Denied::BadHost));
    }

    #[test]
    fn rejects_a_foreign_origin() {
        let h = headers(&[
            ("host", "127.0.0.1:51234"),
            ("origin", "https://evil.example.com"),
            ("authorization", "Bearer s3cret-token-value"),
        ]);
        assert_eq!(check(&h, &state()), Err(Denied::BadOrigin));
    }

    #[test]
    fn accepts_a_cross_site_fetch_from_the_allowed_origin() {
        // Every legitimate request is cross-site: the renderer is served from
        // `app://local` and the API from loopback. A rule that refuses
        // `Sec-Fetch-Site: cross-site` rejects the app itself, so there is not
        // one — and this test exists to stop it being reintroduced.
        let h = headers(&[
            ("host", "127.0.0.1:51234"),
            ("origin", "app://local"),
            ("sec-fetch-site", "cross-site"),
            ("authorization", "Bearer s3cret-token-value"),
        ]);
        assert_eq!(check(&h, &state()), Ok(()));
    }

    #[test]
    fn rejects_a_wrong_token() {
        let h = headers(&[
            ("host", "127.0.0.1:51234"),
            ("authorization", "Bearer wrong-token-value!"),
        ]);
        assert_eq!(check(&h, &state()), Err(Denied::BadToken));
    }

    #[test]
    fn rejects_a_missing_token() {
        let h = headers(&[("host", "127.0.0.1:51234")]);
        assert_eq!(check(&h, &state()), Err(Denied::MissingToken));
    }

    #[test]
    fn a_token_prefix_is_not_enough() {
        // Guards against a length-insensitive comparison.
        let h = headers(&[
            ("host", "127.0.0.1:51234"),
            ("authorization", "Bearer s3cret"),
        ]);
        assert_eq!(check(&h, &state()), Err(Denied::BadToken));
    }

    #[test]
    fn accepts_localhost_spelling_of_the_bound_port() {
        let h = headers(&[
            ("host", "localhost:51234"),
            ("authorization", "Bearer s3cret-token-value"),
        ]);
        assert_eq!(check(&h, &state()), Ok(()));
    }

    #[test]
    fn rejects_the_right_hostname_on_the_wrong_port() {
        let h = headers(&[
            ("host", "127.0.0.1:9999"),
            ("authorization", "Bearer s3cret-token-value"),
        ]);
        assert_eq!(check(&h, &state()), Err(Denied::BadHost));
    }
}
